### ISSUE TITLE
No explicitly declared versions of upstream-managed components in pom-trakem2

### ISSUE THREAD

**Issue by hinerm** [trakem2/TrakEM2#12]
e.g. mpicbg's version is overridden from Fiji. This causes problems because Fiji can only ship one version, which needs to be the one managed in pom-fiji.

The ideal workflow would be:
* Update version in pom-fiji
* Release pom-fiji
* Update pom-trakem2 to use new pom-fiji version

**Comment by hinerm** [comment]
@axtimwalde happy to discuss during the hackathon next week

**Comment by axtimwalde** [comment]
@hinerm sure!

**Comment by ctrueden** [comment]
TrakEM2 now inherits all components from upstream, except for postgresql and jai, which it manages at its level (i.e.: it does not override them, because no non-TrakEM2 components use these).
