### ISSUE TITLE
Java3D dependency in Java 6 and 8

### ISSUE THREAD

**Issue by axtimwalde** [trakem2/TrakEM2#13]
Summarizing previous discussion on other channels:

@axtimwalde: Did you have a chance to put the vecmath stuff into a separate package that is independent of Java8?

@ctrueden: Well, org.scijava:vecmath:1.6.0-scijava-2 is compatible with Java 1.5+; we could upload it to the Fiji update site if you wish. We would need to release a version of TrakEM2 that depends on the new vecmath, but _not_ the new j3dcore or j3dutils artifacts though... more trouble than it's worth if you ask me, but ultimately up to you.

[...]

@ctrueden: Yes, Java 6 is most useful for Apple users, because Oracle Java 7 + 8 still have critical bugs. Java 3D 1.5.2 does work with Apple Java 6, and Java 3D 1.6.0-scijava-2 does work with Oracle Java 8, except there are still some bugs...

**Comment by axtimwalde** [comment]
Solution suggested by @ctrueden: Keep current (frozen) version of TrakEM2 on Java 6 update site, put new version on Java 8 update site.  I think this will break soon because TrakEM2 has too many dependencies.  If any of these dependencies receives a Java 6 compatible upgrade that is incompatible with TrakEM2, TrakEM2 Java 6 will break.  That means I will have to bugfix on two fronts which I would prefer to avoid.  If it's easy enough to have  org.scijava:vecmath:1.6.0-scijava-2 as a separate component on Fiji (both Java 6 and 8, because it does not require Java 8), I would strongly prefer this solution.  The changes in https://github.com/trakem2/TrakEM2/commit/df3be0179cdea2e2c898bb049ddb0e3689da1bf8 should cover this (except for dependencies in pom.xml which is easy).

**Comment by ctrueden** [comment]
> f any of these dependencies receives a Java 6 compatible upgrade that is incompatible with TrakEM2, TrakEM2 Java 6 will break.

If we create a `java6` branch of sc.fiji:fiji, which we keep aligned with what's on the main Fiji & ImageJ update sites, then we can use the melting pot script to test for these breakages. (Though I suppose TrakEM2 is unfortunately light on unit tests...)

> That means I will have to bugfix on two fronts which I would prefer to avoid.

100% agreed!

> If it's easy enough to have org.scijava:vecmath:1.6.0-scijava-2 as a separate component on Fiji (both Java 6 and 8, because it does not require Java 8), I would strongly prefer this solution.

Sure, go for it then.

**Comment by ctrueden** [comment]
@axtimwalde For what it's worth, due to your concerns above, @hinerm and I agreed to completely freeze the ImageJ and Fiji update sites until the Java 8 migration is totally complete. So we have been pushing _all_ updates to the Java-8 update site only, now. Hopefully this avoids the skew you fear.

**Comment by axtimwalde** [comment]
@ctrueden thanks for letting me know.

**Comment by ctrueden** [comment]
I [released `pom-trakem2` version `2.0.0` with all TrakEM2 components including `TrakEM2_` version `1.0h`](https://github.com/trakem2/TrakEM2/commit/046754ed6a918f6e451a4618d33bd00e83a3e81e), and uploaded it all to the Java-8 update site. I did very little testing, although I did verify that zooming now works as expected. Further testing from the community would be very welcome.
