### ISSUE TITLE
AreaList objects are not added to the 3D Viewer

### ISSUE THREAD

**Issue by acardona** [trakem2/TrakEM2#14]
But volumes are, e.g. a stack in orthoslice mode.

The progress bar traverses to the end, but then, upon query, the Image3DUniverse contains only the orthoslice and none of the meshes that would represent the arealists.

To reproduce:
1. Add an AreaList to a TrakEM2 volume. Paint it in at least 2 sections.
2. With the AreaList selected, right-click and pick "Show in 3D".
3. From the Jython Interpreter, type the following:

```
#####
d = Display3D.getDisplay(Display.getFront().getLayerSet())
d.universe.getContents()
#####
```

... which will print an empty list. Nothing was added, despite no error being thrown.

All of this, with java 1.8 and latest fiji.

When adding the Content objects manually, everything works:

```
#####
from ini.trakem2.display import Display, Display3D

ls = Display.getFront().getLayerSet()
d3d = Display3D.getDisplay(ls)

for zd in ls.getZDisplayables():
  if zd.isVisible():
    pt = zd.project.findProjectThing(zd)
    c = d3d.createMesh(pt, zd, 4).call()
    d3d.universe.addContentLater(c)
 #####
```

Realize that the script above was written by looking at the Display3D class and pretty much copying what it does.

**Comment by acardona** [comment]
Hi @bimoelle if you have a fix for this issue it would be lovely if you were to push it upstream. Thank you!

**Comment by bimoelle** [comment]
Hi @acardona unfortunately there went something wrong with the reference to this issue - our commit does not solve this issue, but is dedicated to another issue in another (external) repo... I am not sure why this happened, maybe Github tried to automatically link our commit to an issue on Github and found the one with the same number here...?! Remains strange. So, I am sorry that I cannot contribute anything at this point.
