### ISSUE TITLE
ScriptRunner not found

### ISSUE THREAD

**Issue by axtimwalde** [trakem2/TrakEM2#21]
@ctrueden @acardona In a fresh Fiji download, running a preprocessor script fails with
```
java.lang.ClassNotFoundException: common.ScriptRunner
```

**Comment by acardona** [comment]
Might be in the Fiji Legacy update site for mysterious reasons.

**Comment by ctrueden** [comment]
The `common.ScriptRunner` class is part of fiji-scripting, which only ships as part of Fiji-Legacy.

What is a "preprocessor script"? What steps can I follow to reproduce?

**Comment by davidhildebrand** [comment]
Ran into this problem recently.
@ctrueden Can be reproduced by adding a pre-processor script in the TrakEM2 GUI by right clicking on a layer > Script > Set pre-processor script layerwise... > choosing a simple script such as that outlined in the "B. Create a preprocessor script and set it to all images" section at https://imagej.net/TrakEM2
@acardona Can confirm that Fiji-Legacy fixes the support.
