### ISSUE TITLE
Update pom-scijava to 30.0.0

### ISSUE THREAD

**Issue by hinerm** [trakem2/TrakEM2#27]
As of pom-scijava 30.0.0, the Simple_Neurite_Tracer] dependency can now be updated to `org.morphonets:SNT`.

https://github.com/trakem2/TrakEM2/blob/94e44580ebecafe036aeb96fa3150b7e4fa6f7af/pom.xml#L218-L226 

Some migration is necessary as TrakEM2 as the `ini.trakem2.display.Polyline` class is no longer present in `SNT`.

**Comment by hinerm** [comment]
@axtimwalde @acardona can one of you make this change? I do not have commit rights and am not sure how `Polyline` usage should be updated.

**Comment by imagejan** [comment]
@hinerm wrote:
> the `ini.trakem2.display.Polyline` class is no longer present in SNT.

[`Polyline`](https://github.com/trakem2/TrakEM2/blob/94e44580ebecafe036aeb96fa3150b7e4fa6f7af/src/main/java/ini/trakem2/display/Polyline.java) *is* part of TrakEM2.

**Comment by hinerm** [comment]
> [`Polyline`](https://github.com/trakem2/TrakEM2/blob/94e44580ebecafe036aeb96fa3150b7e4fa6f7af/src/main/java/ini/trakem2/display/Polyline.java) _is_ part of TrakEM2.

argh. Of course, thank you. `Polyline` itself needs its imports updated to the new packages:
```
import sc.fiji.snt.Path;
import sc.fiji.snt.SearchInterface;
import sc.fiji.snt.SearchProgressCallback;
import sc.fiji.snt.TracerThread;
```

And [these lines](https://github.com/trakem2/TrakEM2/blob/94e44580ebecafe036aeb96fa3150b7e4fa6f7af/src/main/java/ini/trakem2/display/Polyline.java#L716-L717) need to be updated for changed API/field visibility.

**Comment by imagejan** [comment]
https://github.com/trakem2/TrakEM2/blob/94e44580ebecafe036aeb96fa3150b7e4fa6f7af/src/main/java/ini/trakem2/display/Polyline.java#L716

This can be replaced by `result.size()`.

https://github.com/trakem2/TrakEM2/blob/94e44580ebecafe036aeb96fa3150b7e4fa6f7af/src/main/java/ini/trakem2/display/Polyline.java#L717

That one is more difficult. The `getXYZUnscaled()` method was removed here:

https://github.com/morphonets/SNT/commit/8f74838884911f4276b09764372d277378872ba4#diff-9d18d39571ccc3273052cc8eb8a38f88b03cb2ef6edccde1f06956dab28288ae

@tferr can you suggest an alternative? Or can we re-introduce that method?

**Comment by hinerm** [comment]
> @tferr can you suggest an alternative? Or can we re-introduce that method?

I am assuming the [individual X-Y-Z methods](https://github.com/morphonets/SNT/blob/3274c524178fbea76b976678f4babd53076b0f3b/src/main/java/sc/fiji/snt/Path.java#L939-L949) can be looped over from `0..result.size()`?

**Comment by tferr** [comment]
Yes! see #25 (https://github.com/trakem2/TrakEM2/pull/25/commits/07d67a947fd7c23d2b608c4b46b55f50338482cf?diff=split&w=1). The PR may be a bit outdated, but it does exactly that.

**Comment by hinerm** [comment]
> Yes! see #25 ([07d67a9?diff=split&w=1](https://github.com/trakem2/TrakEM2/commit/07d67a947fd7c23d2b608c4b46b55f50338482cf?diff=split&w=1)). The PR may be a bit outdated, but it does exactly that.

@tferr oh perfect. I opened https://github.com/trakem2/TrakEM2/pull/28 which includes your changes and updates the pom as well, now that we have something to pin to.
